### ISSUE TITLE
Consolidate past test notebooks together into this one repo

### ISSUE THREAD

**Issue by slarson** [openworm/tests#5]
- [x] [EGL-19 notebook](https://github.com/openworm/ChannelWorm/blob/master/tests/SCU_IVCurve_Model.ipynb)
- [x] [Muscle model notebook](https://github.com/openworm/CElegansNeuroML/blob/sciunit/CElegans/pythonScripts/c302/notebooks/RunMuscleModel-SciUnit.ipynb)

**Comment by rgerkin** [comment]
Done.
