### ISSUE TITLE
Post build failures of the MuscleModel.ipynb notebook due to absence of c302 module.

### ISSUE THREAD

**Issue by russelljjarvis** [openworm/tests#8]
I am finding that installing CElegansNeuroML and ChannelWorm is still not sufficient to to import the c302 module.

**Comment by rgerkin** [comment]
Are you running `pip install -e .[channels,cells] --process-dependency-links` from the tests directory?  If you don't you may be targeting the wrong branch of CElegansNeuroML which does not contain an importable c302.   I am able to run and pass all the tests (which include importing c302) when I install using the `pip install -e .[channels,cells] --process-dependency-links`.

**Comment by rgerkin** [comment]
I have a working Docker container if you want to use that.

**Comment by russelljjarvis** [comment]
Oh I didn't notice the argument .[channels,cells] to pip install.

Yes please link me to the Dockerfile.

**Comment by rgerkin** [comment]
https://github.com/openworm/tests/blob/master/Dockerfile
